# Generated by Django 3.1.12 on 2026-04-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=8)),
                ('owner_photo', models.ImageField(upload_to='owner_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=8)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PetRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('allergies', models.TextField(blank=True)),
                ('vaccinations_notes', models.TextField(blank=True)),
                ('medical_history', models.FileField(upload_to='medical_histories/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_api.petowner')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('diagnosis_notes', models.TextField()),
                ('reason', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('status', models.CharField(choices=[('Scheduled', 'S'), ('Completed', 'C'), ('Cancelled', 'X')], max_length=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_api.petrecord')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_api.veterinarian')),
            ],
        ),
    ]
