# Generated by Django 3.1.12 on 2026-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='diagnosis_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='treatment_plan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
