# Generated by Django 3.1.12 on 2026-05-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0002_auto_20260429_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrecord',
            name='medical_history',
        ),
        migrations.CreateModel(
            name='MedicalRecordEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_histories/')),
                ('notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_entries', to='clinic_api.petrecord')),
            ],
        ),
    ]
